### ISSUE TITLE
read and apply DQ filter to biocache query

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#58] opened 2020-03-11 02:06 UTC
initially add filters to the fq in the URL

**Comment by alexhuang091** [comment] 2020-03-15 23:26
Hi guys, as you know a request can have multiple fqs and different fq can be on same fields, for example

`&fq = -(month:"11" OR month:"12) & fq = -month:"10" & fq = -(month:"9" OR month:"8")` this effectively is to exclude month from Aug to Dec

What I originally thought is, if say default filters also have a fq on month field, instead of directly appending it, we analyze and try to merge it into user-specified fqs. So that 
`&fq = A &fq = B &fq = C` after merging can be a `&fq = A &fq = B &fq = D` or eventually `&fq = D`

This solution at least has 2 problems: difficult to implement, many cases to consider to properly merge. 
Second, if merge is successful, a new fq (`&fq=D` in above example)is generated and  when the result is shown to user, that fq is neither a user specified filter nor a default filter since it's a merged filter.

If we do appending, say if user input is <br>`&fq = -(month:"11" OR month:"12) &fq = -month:"10" &fq = -(month:"9" OR month:"8") `<br>and default `&fq = month:"1"`, <br>eventually it's `&fq = -(month:"11" OR month:"12) &fq = -month:"10" &fq = -(month:"9" OR month:"8") &fq = month:"1"` which actually only returns those with month in Jan. 

The advantage is we can show user clearly which are user-specified fqs which are default filters.

**Comment by alexhuang091** [comment] 2020-03-16 00:23
The reason I want to merge is, currently in ALA occurrence UI, it's totally possible to construct a query like `fq=(month:"01" OR month:"02" OR month:"03" OR month:"04")&fq=(month:"01" OR month:"02" OR month:"03")&fq=(month:"01" OR month:"02")&fq=month:"01"` in it actually only the last fq works.

Not sure if solr internally smartly handles it.

**Comment by M-Nicholls** [comment] 2020-03-20 00:34
be aware of the URL getting longer if the default DQ filers are added multiple times  - e.g. when copy-paste the URL

**Comment by alexhuang091** [comment] 2020-03-20 02:03
> be aware of the URL getting longer if the default DQ filers are added multiple times - e.g. when copy-paste the URL

copy - paste is fixed now. Before appending default fq, check if it already exists in user fq. If yes, don't apply it.

**Comment by alexhuang091** [comment] 2020-03-24 00:26
code review https://upsource.ala.org.au/biocache-hubs/review/BH-CR-9

**Comment by ansell** [comment] 2020-03-30 19:24
Facet queries are not getting the the data quality filters applied to them consistently at this point. See this comment thread for more details on the regression https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/338#issuecomment-603637722

**Closed** 2021-03-11 21:49 UTC
Labels: 1
