### ISSUE TITLE
Add duplicate user assertion info the record details page in the user assertion UI

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#208] opened 2020-11-18 03:27 UTC
Add:
duplicate
duplicate type
duplicate of - representative record (as as working link)

**Comment by sbearcsiro** [comment] 2020-11-30 00:47
https://upsource.ala.org.au/biocache-hubs/review/BH-CR-56

**Comment by M-Nicholls** [comment] 2020-12-09 22:14
field label is repeated - Duplicate Record ID:* is used for both record ID and reason

**Comment by M-Nicholls** [comment] 2021-02-11 21:39
show more duplicate details in record details page:

As per record preview:
Duplicate record - flagged by Miles Nicholls

Reason: Tissue sample

record ID
scientific name
state
latitude
longitude
eventDate

View duplicated record

Comment: test duplicate

**Comment by M-Nicholls** [comment] 2021-03-24 21:30
update to the text "This record is a same occurrence of this record:"

Duplicate record - flagged by Miles Nicholls

Reason: Same occurrence

This record you are viewing is a same occurrence duplicate of this record:

    record ID: cc50504c-87e1-4100-bec1-88d70fa49fd2

    scientific name: Rhytidoponera

    state: Western Australia

    latitude: 115.8603325

    longitude: -32.0918113

    eventDate: 2017-01-29
View duplicated record

Comment: testing

Date created: 2021-03-25 08:24:45

**Comment by nickdos** [comment] 2021-03-24 22:25
> This record you are viewing is a same occurrence duplicate of this record:

Is that the intended text? It could be worded better. E.g. you don't need to state the obvious "this record you are viewing", I think you can take that for granted as it what the user is seeing on the page.

"is the same occurrence duplicate of this record" doesn't make sense - is the user viewing the"record you are viewing or "this record" - they seem to be 2 different records but the text is saying they the same record, so it is quite confusing.  

Also, It is saying this record "is the same duplicate" is can't be the same duplicate - it can only be the "same record" or "a duplicate" but "same duplicate" is not a thing.

**Comment by M-Nicholls** [comment] 2021-03-24 23:47
The format I was using is: "This record you are viewing is a <duplicate type> duplicate of this record:" which doesn't look great with the "same occurrence" duplicate type.  Also, what I'm looking for is the text is to be consistent with the flag an issue dialogue where there's a table:

This record you are viewing | Is a tissue sample of | This record ID provided

![image](https://user-images.githubusercontent.com/9424545/112397609-8865aa00-8d56-11eb-9fb8-f51cb9c0a037.png)

"This record you are viewing" gives direction to the annotation because it's not visible on the other record and important in the tissue sample duplicate

We could tune the wording up a bit depending which duplicate type it is:

This record you are viewing is the same occurrence as this record:
This record you are viewing is a tissue sample of this record:
This record you are viewing is a split specimen of this record:

**Comment by nickdos** [comment] 2021-03-25 01:29
Yes, that "tuning" is good.  The only suggestion I have is about the "same occurrence" - the "regular duplicate" is usually not exactly the same (there are often minor differences such as the dataresource being different) and thus a user might think - `well it's not the "same" record, so I won't choose that option`.  How about just `duplicate occurrence`?

`This record you are viewing` could be simplified to `This record`.

**Comment by M-Nicholls** [comment] 2021-03-29 02:55
Good suggestions, thanks Nick.

Let's go with:
This record is a duplicate occurrence of this record:
This record is a tissue sample of this record:
This record is a split specimen of this record:

We also need to update the duplicate type drop down and the wording in the record preview table to replace "same occurrence" with "duplicate occurrence" and "This record you are viewing" with "This record"

**Closed** 2021-04-06 22:28 UTC
Labels: 1
